-- TABLE CREATIONS

create table
  public.barrels_available_for_purchase (
    id bigint generated by default as identity not null,
    sku text not null,
    ml_per_barrel bigint not null,
    potion_type integer[] not null,
    price bigint not null,
    constraint barrels_available_for_purchase_pkey primary key (id),
    constraint barrels_available_for_purchase_id_key unique (id),
    constraint barrels_available_for_purchase_sku_key unique (sku)
  ) tablespace pg_default;

create table
  public.carts (
    cart_id bigint generated by default as identity not null,
    constraint carts_pkey primary key (cart_id),
    constraint carts_id_key unique (cart_id)
  ) tablespace pg_default;

create table
  public.cart_items (
    cart_id bigint not null,
    catalog_id bigint not null,
    potion_quantity bigint not null,
    constraint cart_items_pkey primary key (cart_id, catalog_id),
    constraint cart_items_cart_id_fkey foreign key (cart_id) references carts (cart_id),
    constraint cart_items_catalog_id_fkey foreign key (catalog_id) references catalog (catalog_id)
  ) tablespace pg_default;

create table
  public.catalog (
    quantity bigint not null default '0'::bigint,
    potion_sku text not null,
    potion_name text not null,
    potion_price bigint not null default '1'::bigint,
    potion_type integer[] not null,
    catalog_id bigint generated by default as identity not null,
    constraint catalog_pkey primary key (catalog_id),
    constraint catalog_catalog_id_key unique (catalog_id),
    constraint catalog_potion_sku_key unique (potion_sku),
    constraint catalog_potion_type_key unique (potion_type)
  ) tablespace pg_default;

create table
  public.cha_ching (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    gold bigint not null default '0'::bigint,
    constraint cha_ching_pkey primary key (id)
  ) tablespace pg_default;

create table
  public.customer_purchases (
    cart_id bigint not null,
    customer_id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    constraint customer_purchases_pkey primary key (cart_id, customer_id),
    constraint customer_purchases_cart_id_fkey foreign key (cart_id) references carts (cart_id),
    constraint customer_purchases_customer_id_fkey foreign key (customer_id) references customer_visits (id)
  ) tablespace pg_default;

create table
  public.customer_visits (
    id bigint generated by default as identity not null,
    created_at timestamp with time zone not null default now(),
    customer_name text not null,
    character_class text not null,
    level bigint not null,
    constraint customer_visits_pkey primary key (id),
    constraint customer_visits_id_key unique (id)
  ) tablespace pg_default;

create table
  public.liquid_inventory (
    color text not null,
    num_ml bigint not null default '0'::bigint,
    id bigint generated by default as identity not null,
    potion_type integer[] not null,
    constraint liquid_inventory_pkey primary key (id),
    constraint liquid_inventory_color_key unique (color),
    constraint liquid_inventory_id_key unique (id),
    constraint liquid_inventory_potion_type_key unique (potion_type)
  ) tablespace pg_default;

create table
  public.storage_capacity (
    id bigint generated by default as identity not null,
    potion_capacity bigint not null default '1'::bigint,
    ml_capacity bigint not null default '1'::bigint,
    constraint storage_capacity_pkey primary key (id),
    constraint storage_capacity_id_key unique (id)
  ) tablespace pg_default;

-- INITIAL DATA POPULATION -- 

-- FOR catalog
INSERT INTO catalog (potion_type, potion_sku, potion_name, potion_price) VALUES
('{0, 100, 0, 0}', '000R100G000B000D', '000R100G000B000D', 50),
('{100, 0, 0, 0}', '100R000G000B000D', '100R000G000B000D', 50),
('{0, 0, 100, 0}', '000R000G100B000D', '000R000G100B000D', 60),
('{0, 50, 50, 0}', '000R050G050B000D', '000R050G050B000D', 55),
('{50, 0, 50, 0}', '050R000G050B000D', '050R000G050B000D', 55),
('{50, 50, 0, 0}', '050R050G000B000D', '050R050G000B000D', 50),
('{0, 0, 0, 100}', '000R000G000B100D', '000R000G000B100D', 15),
('{25, 25, 25, 25}', '025R025G025B025D', '025R025G025B025D', 44);

-- FOR cha_ching
INSERT INTO cha_ching (gold) VALUES (100)

-- FOR liquid_inventory
INSERT INTO liquid_inventory (potion_type, color) VALUES
('{0, 0, 0, 1}', 'DARK'),
('{0, 1, 0, 0}', 'GREEN'),
('{1, 0, 0, 0}', 'RED'),
('{0, 0, 1, 0}', 'BLUE');
